# Generated by Django 4.2.1 on 2024-08-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_rename_name_user_first_name_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
